# Generated by Django 6.1.1 on 2026-09-03 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provedores', '0001_initial'),
        ('rfps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prazo_instalacao_dias', models.PositiveIntegerField()),
                ('sla_disponibilidade', models.DecimalField(decimal_places=2, help_text='Ex: 99.5 (%)', max_digits=5)),
                ('observacoes', models.TextField(blank=True)),
                ('enviada_em', models.DateTimeField(auto_now_add=True)),
                ('provedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='provedores.provedor')),
                ('rfp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='rfps.rfp')),
            ],
            options={
                'unique_together': {('rfp', 'provedor')},
            },
        ),
    ]
