# Generated by Django 6.1.1 on 2026-09-03 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('tipo_link', models.CharField(choices=[('banda_larga', 'Banda larga empresarial'), ('dedicado', 'Link dedicado'), ('ponto_a_ponto', 'Transporte ponto a ponto')], max_length=20)),
                ('cep', models.CharField(max_length=9)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('velocidade_download_mbps', models.PositiveIntegerField()),
                ('velocidade_upload_mbps', models.PositiveIntegerField()),
                ('prazo_cotacao', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
